version: '3.5'

services:
  mongo:
    image: mongo:5.0.14
    restart: always
    ports:
      - "127.0.0.1:${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - "127.0.0.1:${MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
    depends_on:
      - mongo

  redis:
    image: redis
    restart: always
    ports:
      - "127.0.0.1:${REDIS_PORT}:${REDIS_PORT}"

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - "127.0.0.1:${REDIS_COMMANDER_PORT:-8081}:8081"
    environment:
      REDIS_HOSTS: local:redis:${REDIS_PORT}
    depends_on:
      - redis

  app:
    build: 
      dockerfile: Dockerfile
      context: "."
    restart: always
    environment:
      - NODE_ENV=development
      - APP_PORT=${APP_PORT}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mongo
      - redis

volumes:
  mongo: