# This workflow aim to build and deploy the development version of PrestaShop
name: Build And Deploy Development Branch

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-deploy:
    name: Build and Deploy

    runs-on: ubuntu-latest

    env:
      RELEASE_DIR: '/tmp/mern-commerce'

    #todo: add build tests

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ env.GH_BRANCH }}

      - name: Prepare directories
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.USERNAME }}
          script_stop: true
          port: ${{ secrets.PORT }}
          script: |
            rm -rf ${{ env.RELEASE_DIR }}
            mkdir -p ${{ env.RELEASE_DIR }}
      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./
          remote: ${{ env.RELEASE_DIR }}
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          privateKey : ${{ secrets.SSH_KEY }}

      # https://devdocs.prestashop-project.org/1.7/basics/keeping-up-to-date/upgrade/
      - name: Docker Compose Up
        uses: appleboy/ssh-action@v0.1.5
        env:
          PROXY_PORT: ${{ secrets.PROXY_PORT }}
          APP_PORT: ${{ secrets.APP_PORT }}
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          MONGO_PORT: ${{ secrets.MONGO_PORT }}
          MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          MONGO_EXPRESS_PORT: ${{ secrets.MONGO_EXPRESS_PORT }}
          REDIS_COMMANDER_PORT: ${{ secrets.REDIS_COMMANDER_PORT }}

        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          script_stop: true
          envs: "PROXY_PORT,APP_PORT,MONGO_HOST,MONGO_PORT,MONGO_DATABASE,MONGO_USER,MONGO_PASSWORD,REDIS_HOST,REDIS_PORT,MONGO_EXPRESS_PORT,REDIS_COMMANDER_PORT"
          script: |
            export PROXY_PORT=${PROXY_PORT}
            export APP_PORT=${APP_PORT}
            export MONGO_HOST=${MONGO_HOST}
            export MONGO_PORT=${MONGO_PORT}
            export MONGO_DATABASE=${MONGO_DATABASE}
            export MONGO_USER=${MONGO_USER}
            export MONGO_PASSWORD=${MONGO_PASSWORD}
            export REDIS_HOST=${REDIS_HOST}
            export REDIS_PORT=${REDIS_PORT}
            export MONGO_EXPRESS_PORT=${MONGO_EXPRESS_PORT}
            export REDIS_COMMANDER_PORT=${REDIS_COMMANDER_PORT}
            cd ${{ env.RELEASE_DIR }}
            docker-compose up -d --no-deps --build